### ISSUE TITLE
Implement Caching System to Improve Performance and Reduce API Calls

### ISSUE THREAD

**Issue by dinesh-pasupuleti** [jayjoshi1400/Sentimental-Analyzer-Pro#1]
We need to implement a caching system for the news scraper to improve performance and reduce unnecessary API calls.

**Comment by jayjoshi1400** [comment]
I've implemented a basic caching system for the news scraper to reduce API calls. The scrapper now checks the cache before making API calls. Can see drastic improvement already. Working to optimize it further

**Comment by jayjoshi1400** [comment]
Added functionality to cache the sentiment data generated by the ML model to further reduce redundant API calls. Both the news and sentiment caches are stored for 1 hour. Closing this issue
