### ISSUE TITLE
Reddit Analysis

### ISSUE THREAD

**Issue by jayjoshi1400** [jayjoshi1400/Sentimental-Analyzer-Pro#5]
The current tool includes several social media analyzers, but doesn't yet support Reddit. With this feature, users should be able to analyze Reddit posts simply by pasting link.

**Comment by dinesh-pasupuleti** [comment]
I have implemented this feature using the VADEE sentiment analyzer. Users can now copy and paste Reddit post URLs to view a detailed sentiment analysis of the post titles.
